server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/books/**
        - id: employeeservice
          uri: lb://employeeservice
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10 #trong 1s nap lai 10 token
                redis-rate-limiter.burstCapacity: 20 #toi da 20 packega token
                redis-rate-limiter.requestedTokens: 1 # so luong request tieu thu n token
            - KeyAuthFilter
    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        fetchRegistry: true
        registerWithEureka: true
  data:
    redis:
      port: 6379
      host: localhost

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/