spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:default-group}
  mail:
    host: smtp.gmail.com
    port: 587
    username: webshopcompany1224@gmail.com
    password: ddos zyua xrmr oiwc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp